-- Planner: one row per schedule.
--
-- The shape mirrors ProjectDoc in src/engine/types.ts exactly. The app's unit
-- of persistence has always been the whole document — the store clones it,
-- mutates it, reschedules and writes it back, and undo is a stack of whole
-- documents (EDD D-008) — so tasks and links are jsonb rather than child
-- tables. Normalising here would mean rewriting the store, not the schema.
--
-- Idempotent: safe to run more than once.

create table if not exists public.projects (
  -- text, not bigint identity, because the id is ProjectDoc.id: generated by
  -- the app and already referenced by every link in the document.
  id          text primary key,
  name        text not null,
  data_date   date not null,                                      -- ProjectDoc.dataDate
  tasks       jsonb not null default '[]'::jsonb,                  -- Task[]
  links       jsonb not null default '[]'::jsonb,                  -- Link[]
  updated_at  timestamptz not null default now(),                  -- ProjectDoc.updatedAt

  -- Which browser wrote last. A realtime event carrying your own client id is
  -- your own echo, and is ignored rather than re-applied.
  client_id   text,

  -- The soft editor lock (PRD Q-6). Claimed on first edit, kept alive by a
  -- heartbeat, and considered abandoned 90s after the last one. There is no
  -- explicit release, because a closed laptop never sends one.
  editor_id   text,
  editor_seen timestamptz,

  -- So the project list can be built without pulling every task down. Depends
  -- on tasks being an array, which the check constraints below guarantee.
  task_count  int generated always as (jsonb_array_length(tasks)) stored,

  -- Fail the write, rather than the generated column, if anything ever sends
  -- an object or a scalar where the document expects a list.
  constraint projects_tasks_is_array check (jsonb_typeof(tasks) = 'array'),
  constraint projects_links_is_array check (jsonb_typeof(links) = 'array')
);

create index if not exists projects_updated_at_idx on public.projects (updated_at desc);

-- ---------------------------------------------------------------------------
-- Access. The anon key reads and nothing else; every write arrives through a
-- service-role function in api/, behind the shared passcode.
-- ---------------------------------------------------------------------------

alter table public.projects enable row level security;

-- RLS does not apply to the table owner unless forced. Roles with BYPASSRLS —
-- service_role — are unaffected, so writes from api/ still work.
alter table public.projects force row level security;

drop policy if exists projects_read_anon on public.projects;
create policy projects_read_anon on public.projects
  for select to anon, authenticated using (true);

-- Belt as well as braces. Supabase grants the public roles full DML on new
-- tables by default and relies on RLS to stop them; taking the grant away too
-- means a permissive policy added by accident later still cannot write.
grant select on public.projects to anon, authenticated;
revoke insert, update, delete, truncate on public.projects from anon, authenticated;

-- ---------------------------------------------------------------------------
-- Realtime. Adding a table twice is an error, so check first.
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'projects'
  ) then
    alter publication supabase_realtime add table public.projects;
  end if;
end
$$;

comment on table public.projects is
  'One row per schedule, mirroring ProjectDoc. Read by the anon key; written only by the service role from api/.';
